project_id = "xyqbvgbtspcjkyioxeiu"

[functions.admin-list-users]
verify_jwt = true

[functions.admin-deactivate-user]
verify_jwt = true

[functions.admin-reactivate-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-send-password-reset]
verify_jwt = true

[functions.admin-list-user-log]
verify_jwt = true
